### ISSUE TITLE
Add web socket c++ library: websocketpp

### ISSUE THREAD

**Issue by grahamaj** [smanders/externpro#131]
License: BSD https://github.com/zaphoyd/websocketpp/blob/master/COPYING
Github repo: https://github.com/zaphoyd/websocketpp
Web page:  https://www.zaphoyd.com/websocketpp/

**Comment by smanders** [comment]
completed with commit https://github.com/smanders/externpro/commit/e00edbfb1c7d1ce82d9ea14dd91a8a88c19ff2a8 to dev branch
