### ISSUE TITLE
mkpatch step needs some serialization to support parallel builds

### ISSUE THREAD

**Issue by sbowler** [smanders/externpro#135]
Running a mkpatch on Windows results in output similar to 

```
 HEAD is now at 86e6ad7... Merge pull request #1 from sbowler/patch
         Performing update step for 'mgrs_repo'
         Fetching origin
         Performing patch step for 'mgrs_repo'
         Performing configure step for 'mgrs_repo'
     1>
CUSTOMBUILD : error : the requested upstream branch 'upstream/master' does not exist
```
Second run results in output similar to 
```
1>  Performing patch step for 'mgrs_repo'
1>  fatal: remote upstream already exists.
```

**Comment by sbowler** [comment]
Looks like this is also broken on Linux so we are dead in the water

**Comment by smanders** [comment]
this brought back some memories of work I had to do to get the mkpatch step working against a newer version of cmake (when we moved from version 3.3.2 to 3.6.2)
https://github.com/smanders/externpro/issues/110

it appears that the mkpatch step works on linux as long as you don't give it too many threads (`make` vs `make -j16`) - and that's probably also the reason for failure on Windows (by default it uses a lot of build threads) - probably some of the steps (`PATCH`, `UPDATE`, `CONFIGURE`) can be run in parallel if there are enough build threads going on - and we need them to be serialized

looking at the mkpatch step changes https://github.com/smanders/externpro/commit/593383f1d7c028b3b240d9629d9670386393b2f8 I'd venture a guess that this problem only exists on projects that have specified an upstream repo

**Comment by smanders** [comment]
completed with commit https://github.com/smanders/externpro/commit/cef3bafa0d139e826098c08d3441c7b1a43b4155 to dev branch
