### ISSUE TITLE
Configure the nodejs build to use os CA store

### ISSUE THREAD

**Issue by grahamaj** [smanders/externpro#140]
This issue is a request to update node and build it with the new flag `--use-openssl-ca` to use openssl's certificate store

**Explaination**
The default behavior for Nodejs is to bundle a snapshot of Mozilla CA (certificate authority) store into the build.  This means that the default CA store is fixed upon building node.  This is also not very helpful for non standard CA's.

As of Node 7.5.0 and the future release 6.11.0 node can be built to use openssl's certificate store

From node's build script readme file:
> Using OpenSSL store allows for external modifications of the store. For most
> Linux and BSD distributions, this store is maintained by the distribution
> maintainers and system administrators. OpenSSL CA store location is dependent on
> configuration of the OpenSSL library but this can be altered at runtime using
> environmental variables.

**Reference**
Openssl CA support for Nodejs 7.5.0: node pull 8334
Node 6.11.0 proposal including the fix for the LTS verison: node pull 13059

**Comment by smanders** [comment]
I discussed this with @grahamaj today -- we'll put this off until the next release of externpro

**Comment by grahamaj** [comment]
@smanders This may be a noop.  It appears that we might be able to use a command line argument at runtime rather than specifying it at build time.  See https://nodejs.org/dist/latest-v6.x/docs/api/cli.html#cli_use_openssl_ca_use_bundled_ca

**Comment by smanders** [comment]
removed "update" label since we now build v6.11.4 which has this feature (**if** we need to modify the build) -- when this issue was first written we needed to **update** to at least 6.11.0 and then add the **enhancement**

**Comment by smanders** [comment]
@grahamaj please let me know if we need to consider doing this in the future... for now I'm closing this issue as "won't fix" - thanks!
