### ISSUE TITLE
gSOAP download URL appears to be broken

### ISSUE THREAD

**Issue by brobeson** [smanders/externpro#141]
I tried to build externpro 17.03.1, on a system which didn't have the projects downloaded. Downloading gSOAP failed with these messages:

```
[ 35%] Performing download step (download, verify and extract) for 'gsoap'
-- verifying file...
       file='/home/brendan/repositories/externpro/release/../_bldpkgs/gsoap_2.7.17.zip'
-- MD5 hash of
    /home/brendan/repositories/externpro/release/../_bldpkgs/gsoap_2.7.17.zip
  does not match expected value
    expected: '6f58cabfc67b4d5eafd1a30057fc4343'
      actual: 'd41d8cd98f00b204e9800998ecf8427e'
-- File already exists but hash mismatch. Removing...
-- Downloading...
   dst='/home/brendan/repositories/externpro/release/../_bldpkgs/gsoap_2.7.17.zip'
   timeout='none'
-- Using src='https://downloads.sourceforge.net/project/gsoap2/gsoap-2.7/gSOAP%202.7.17/gsoap_2.7.17.zip'
-- Retrying...
-- Using src='https://downloads.sourceforge.net/project/gsoap2/gsoap-2.7/gSOAP%202.7.17/gsoap_2.7.17.zip'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://downloads.sourceforge.net/project/gsoap2/gsoap-2.7/gSOAP%202.7.17/gsoap_2.7.17.zip'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://downloads.sourceforge.net/project/gsoap2/gsoap-2.7/gSOAP%202.7.17/gsoap_2.7.17.zip'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://downloads.sourceforge.net/project/gsoap2/gsoap-2.7/gSOAP%202.7.17/gsoap_2.7.17.zip'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://downloads.sourceforge.net/project/gsoap2/gsoap-2.7/gSOAP%202.7.17/gsoap_2.7.17.zip'
CMake Error at /home/brendan/repositories/externpro/release/xpbase/Stamp/gsoap/download-gsoap.cmake:157 (message):
  Each download failed!

    error: downloading 'https://downloads.sourceforge.net/project/gsoap2/gsoap-2.7/gSOAP%202.7.17/gsoap_2.7.17.zip' failed
         status_code: 22
         status_string: "HTTP response code said error"
```

I investigated a bit and I think gSOAP 2.7 has been removed. The closest I could find on SourceForge is 2.8.0 [here](https://sourceforge.net/projects/gsoap2/files/oldreleases/).

**Comment by smanders** [comment]
thanks for the report @brobeson - I've verified the same (with externpro 17.05.1) - and wasn't able to locate version 2.7.17 on sourceforge - I suspect it won't be found and they removed it based on this comment from the link you provided:
> oldreleases contains patched older releases that are secured (versions since 2010-09-20)

oldreleases has back to version 2.8.0 and I'm assuming from that statement that version 2.7.17 isn't considered "secured"

**Comment by smanders** [comment]
I've made `gsoap_2.7.17.zip` available here on github externpro with the commit referenced above

if you need to build an older version of externpro (for example 17.05.1), first do the download step from the dev branch
```bash
cd /path/to/externpro/source
git checkout dev
cd /path/to/build/download
cmake -DXP_STEP=download /path/to/externpro/source
make
```
this will populate (and verify MD5) a `_bldpkgs` directory as a sibling to `/path/to/build/download`
then build the release of externpro you desire
```bash
cd /path/to/externpro/source
git checkout 17.05.1
cd /path/to/build/package
cmake -DXP_STEP=build /path/to/externpro/source
make -j8
make package
```

we need to examine our projects that use externpro and determine whether we ditch gSOAP or update the code to use a newer version - but for now we'll just make the old version available
