### ISSUE TITLE
Security update for nodejs

### ISSUE THREAD

**Issue by grahamaj** [smanders/externpro#144]
There is a known high severity security vulnerability in Nodejs version 6.9.0.  Node should be updated to 6.11.1 or later. (on the 8.x versions it is 8.3.0 or later)  For more details see https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/

**Comment by smanders** [comment]
completed with commit to dev branch (referenced above here in this pull) -- this new version of nodejs won't be available (to VANTAGE) until there is an internpro with two versions of palam (one built with current version of node 6.9.0, another version built against node v6.11.3)

**Comment by grahamaj** [comment]
@smanders, we will also need to spin up a new version of webpro built with the new version.  We might be able to get away without that, but I would rather not take chances with it.

**Comment by smanders** [comment]
just before externpro is released, update to the very latest 6.x.x

**Comment by smanders** [comment]
completed with commit https://github.com/smanders/externpro/commit/61d171103c988f3b39d771b9622a11768566b090 to dev branch
