### ISSUE TITLE
mkpatch geotranz failure

### ISSUE THREAD

**Issue by smanders** [smanders/externpro#245]
the mkpatch step of the geotranz project fails
```
[ 20%] Performing download step (git clone) for 'geotranz_repo'
Cloning into 'geotranz_repo'...
Downloading data/Und_min2.5x2.5_egm2008_WGS84_TideFree_reformatted (150 MB)
Error downloading object: data/Und_min2.5x2.5_egm2008_WGS84_TideFree_reformatted (9e1a4e2): Smudge error: Error downloading data/Und_min2.5x2.5_egm2008_WGS84_TideFree_reformatted (9e1a4e271acaa31fa1160825e95c4a063fde21f69db62ac8030bca34d27319db): batch response: This repository is over its data quota. Purchase more data packs to restore access.

Errors logged to /home/smanders/src/externpro/_bldrepo/xpbase/Source/geotranz_repo/.git/lfs/logs/20190920T104829.08382953.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: data/Und_min2.5x2.5_egm2008_WGS84_TideFree_reformatted: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

fatal: destination path 'geotranz_repo' already exists and is not an empty directory.
fatal: destination path 'geotranz_repo' already exists and is not an empty directory.
-- Had to git clone more than once:
          3 times.
CMake Error at /home/smanders/src/externpro/_bldrepo/xpbase/tmp/geotranz_repo/geotranz_repo-gitclone.cmake:66 (message):
  Failed to clone repository: 'git://github.com/smanders/geotranz.git'


CMakeFiles/geotranz_repo.dir/build.make:89: recipe for target 'xpbase/Stamp/geotranz_repo/geotranz_repo-download' failed
make[2]: *** [xpbase/Stamp/geotranz_repo/geotranz_repo-download] Error 1
CMakeFiles/Makefile2:474: recipe for target 'CMakeFiles/geotranz_repo.dir/all' failed
make[1]: *** [CMakeFiles/geotranz_repo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

failed because `This repository is over its data quota`

**Comment by smanders** [comment]
on 2019.09.09 at 9:28 PM I received an email from GitHub with subject
"At 80% of Git LFS data quota for smanders"
```
Current usage as of 10 Sep 2019 03:28AM UTC:
  Bandwidth: 0.92 GB / 1 GB (92%)
  Storage: 0.14 GB / 1 GB (14%)
```

on 2019.09.10 at 12:23 AM I received another email from GitHub with subject
"At 100% of Git LFS data quota for smanders"
```
Current usage as of 10 Sep 2019 06:23AM UTC:
  Bandwidth: 1.02 GB / 1 GB (102%)
  Storage: 0.14 GB / 1 GB (14%)
```

on 2019.09.10 at 2:39 AM I received another email from GitHub with subject
"Git LFS disabled for smanders"
```
Current usage as of 10 Sep 2019 08:39AM UTC:
  Bandwidth: 1.55 GB / 1 GB (155%)
  Storage: 0.14 GB / 1 GB (14%)
```

I'm not sure how my bandwidth jumped like that in a matter of a few hours at times that I wasn't doing anything with this repo or externpro...

**Comment by smanders** [comment]
the master branch of geotranz has the current version (2.4.2) up to the latest version (3.7) - as extracted from downloads detailed in the commit history https://github.com/smanders/geotranz/commits/master

geotranz version 3.2 introduced a data file too large for the git repo, so it was added via git-lfs https://github.com/smanders/geotranz/commit/7b5ea801f7a19e0203774f06c925a55b73bbe6f5

the current branch needed by externpro is xp2.4.2 https://github.com/smanders/geotranz/tree/xp2.4.2 which doesn't have the large data file

switching the default branch from master to xp2.4.2 https://github.com/smanders/geotranz/settings/branches makes it so the mkpatch step of externpro (which clones the repos) won't checkout the master branch (see the output: `warning: Clone succeeded, but checkout failed.`)

**Comment by smanders** [comment]
completed with commit to dev branch referenced above

**Comment by swainwri** [comment]
I have been downloading the Und_min2.5x2.5_egm2008_WGS84_TideFree_reformatted file to my iOS Geodesy app in the last couple of weeks for testing purposes, perhaps this caused GitHub to flag the file size. I don't know how to convert https://earth-info.nga.mil/GandG/wgs84/gravitymod/egm2008/Und_min2.5x2.5_egm2008_isw=82_WGS84_TideFree.gz to a Und_min2.5x2.5_egm2008_WGS84_TideFree_reformatted file, so hence found your GitHub site.
