### ISSUE TITLE
Need to patch libgit2

### ISSUE THREAD

**Issue by cambamf** [smanders/externpro#329]
libgit2 has a bug where when it calls git_repository_init(), it puts down a link file to a folder that doesn't exist. It is explained here: https://github.com/libgit2/libgit2/issues/5188

It is fixed here: https://github.com/libgit2/libgit2/pull/5151
Unfortunately they also renamed a file so the diff for that pull is big...

**Comment by smanders** [comment]
completed with commit referenced above
verified with builds of Vantage Autotest and CRToolImpl (which both depend on libgit2)
