### ISSUE TITLE
flatbuffers 2.0.6

### ISSUE THREAD

**Issue by smanders** [smanders/externpro#336]
flatbuffers 1.12.0 was added https://github.com/smanders/externpro/issues/283
flatbuffers patch https://github.com/google/flatbuffers/compare/v1.12.0...smanders:xp1.12.0
project file https://github.com/smanders/externpro/blob/22.01/projects/flatbuffers.cmake
use script https://github.com/smanders/externpro/blob/22.01/projects/use/usexp-flatbuffers-config.cmake

flatbuffers 2.0.0 was released 2021.05.10 https://github.com/google/flatbuffers/releases
add function to use script that generates ts files https://isrhub.usurf.usu.edu/webpro/webpro/issues/335#issuecomment-229296 and https://isrhub.usurf.usu.edu/webpro/webpro/blob/bbfbffee7c0cb898a3410b619d9bd40fe10d2f32/projects/use/usexp-flatbuffers-config.cmake

**Comment by smanders** [comment]
maybe some of this modified custom_[command|target] https://isrhub.usurf.usu.edu/ajgraham/VIVID/pull/40/files#diff-68129959ea1d08af65ace715a984d7019ccaf4050fe64db39f39532020eb892e

**Comment by cambamf** [comment]
More or less the command needs to be:
flatc.exe --ts --filename-suffix ".fb" -o <outputDir> <schemas>
Or at least, that is what we have used

**Comment by DeanLanier** [comment]
> More or less the command needs to be: flatc.exe --ts --filename-suffix ".fb" -o Or at least, that is what we have used

It's actually even simpler: `flatc.exe --ts -o outputDir *.fbs` is what I used.

**Comment by smanders** [comment]
flatbuffers 2.0.0 was released 2021.05.10 (as noted in the original description) and is on their releases https://github.com/google/flatbuffers/releases page

but there are also two additional tags: v2.0.5 (2021.12.09) and v2.0.6 (2022.02.15), so I will assume there's good stuff (there are a lot of commits) and go with the latest v2.0.6
* https://github.com/google/flatbuffers/compare/v2.0.0...v2.0.5 163 commits, 544 files changed
* https://github.com/google/flatbuffers/compare/v2.0.5...v2.0.6 78 commits, 271 files changed
* https://github.com/google/flatbuffers/compare/v2.0.0...v2.0.6 241 commits, 679 files changed

**Comment by smanders** [comment]
flatbuffers 2.0.6 patch https://github.com/google/flatbuffers/compare/v2.0.6...smanders:xp2.0.6

**Comment by smanders** [comment]
completed with commits referenced above

**Comment by smanders** [comment]
NOTES
SensorManager changes to leverage the new `xpFlatBuffersBuildTS()` cmake function to generate typescript files
* `git rm -rf WebServer/src/libs/messaging/fb-schemas/`
* add that directory to .gitigore
* call `xpFlatBuffersBuildTS() from WebServer/CMakeLists.txt
* depend on custom target that generates the typescript files
```diff
diff --git a/.gitignore b/.gitignore
index 11a0f26..6c0489f 100644
--- a/.gitignore
+++ b/.gitignore
@@ -16,6 +16,7 @@ WebServer/bin
 WebServer/build
 WebServer/node_modules
 WebServer/spec
+WebServer/src/libs/messaging/fb-schemas/
 WebServer/yarn.lock
 WebServer/yarn-error.log

diff --git a/WebServer/CMakeLists.txt b/WebServer/CMakeLists.txt
index 0bfe9cb..6ca42ec 100644
--- a/WebServer/CMakeLists.txt
+++ b/WebServer/CMakeLists.txt
@@ -60,17 +60,10 @@ set(src_libs_messaging_srcs
 source_group(src\\libs\\messaging FILES ${src_libs_messaging_srcs})
 list(APPEND ${PROJECT_NAME}_prjsrcs ${src_libs_messaging_srcs})
 #######################################
-# TODO: Remove these generated flatbuffer files and add them to the .gitignore file once they are generated with cmake.
-set(src_libs_messaging_fb-schemas_sensor_manager_srcs
-  src/libs/messaging/fb-schemas/sensor_manager/link-status-enum.ts
-  src/libs/messaging/fb-schemas/sensor_manager/simple-cmd-rsp-msg.ts
-  src/libs/messaging/fb-schemas/sensor_manager/simple-sortie-cmd-msg.ts
-  src/libs/messaging/fb-schemas/sensor_manager/simple-sortie-cmd-rsp-msg.ts
-  src/libs/messaging/fb-schemas/sensor_manager/sortie-guide-msg.ts
-  src/libs/messaging/fb-schemas/sensor_manager/sortie-info.ts
-  )
-source_group(src\\libs\\messaging\\fb-schemas\\sensor_manager FILES ${src_libs_messaging_fb-schemas_sensor_manager_srcs})
-list(APPEND ${PROJECT_NAME}_prjsrcs ${src_libs_messaging_fb-schemas_sensor_manager_srcs})
+xpFlatBuffersBuildTS(TARGET ${PROJECT_NAME}
+  SCHEMAS ${SensorManager_SOURCE_DIR}/MessageLib/src/FbSchemas/*.fbs
+  OUTPUT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/libs/messaging/fb-schemas # .gitignore
+  )
 #######################################
 set(src_libs_messaging_messages_srcs
   src/libs/messaging/messages/simple-cmd-rsp-msg.ts
@@ -143,7 +136,7 @@ add_custom_command(
   COMMAND ${CMAKE_COMMAND} -E touch ${CMAKE_CURRENT_BINARY_DIR}/tsBuild.stamp
   COMMENT "Building Web Server"
   WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
-  DEPENDS ${${PROJECT_NAME}_prjsrcs} ${web_shared_stamp}
+  DEPENDS ${${PROJECT_NAME}_prjsrcs} ${PROJECT_NAME}_fbs_ts ${web_shared_stamp}
   )
 add_custom_target(${PROJECT_NAME} ALL
   DEPENDS tsBuild.stamp
```

**Comment by smanders** [comment]
completed with commits referenced above
