### ISSUE TITLE
update the rapidjson version

### ISSUE THREAD

**Issue by smanders** [smanders/externpro#34]
we currently build a snapshot from 2014.09.07 when the tree looked like [this](https://github.com/miloyip/rapidjson/tree/d0f98d2da1e2e6345831dc1ab2c30950417e6490) with 584 commits

we build from this snapshot since there have been no official releases or tags yet

the master branch currently (as of 2015.11.25) has 1,158 commits, so a fair amount of work has been done and we should get updated

v1.0.2 was released 2015.05.14 (993 commits)
v1.0.1 on 2015.04.25 (970 commits)
v1.0.0 on 2015.04.21 (958 commits)

**Comment by smanders** [comment]
> From: Adam J. Graham
Sent: Wednesday, October 12, 2016 9:38 AM
To: Scott M Anderson
Subject: Rapid json

> Hey Scott,
For my eslint integration into the code review tool, I have a need to use rapidjson.  I noticed that externpro downloads a specific git hash instead of a tag because the repo wasn’t yet tagged.  It now has official versions that are tagged.  The latest, 1.1.0, has support for C++ 11 ranged based for loops for its array types.  I find that quite convenient.  I was wondering if we could get the latest official version of that library?
Thanks,
--A.J.

**Comment by grahamaj** [comment]
The change log seems to indicate that most of the changes are additions and fixes.  We might not have to change much code if any at all with the updated. See http://rapidjson.org/md__c_h_a_n_g_e_l_o_g.html

**Comment by smanders** [comment]
v1.1.0 was released 2016.08.25 (1718 commits)
https://github.com/miloyip/rapidjson/releases/tag/v1.1.0

**Comment by smanders** [comment]
completed with [commit](https://github.com/smanders/externpro/commit/12151c48c673c0095c1cdd9f44f8d5ed30c85573) to dev branch
