### ISSUE TITLE
update the activemq url

### ISSUE THREAD

**Issue by brobeson** [smanders/externpro#82]
I tried building externpro this morning and got 404 error when attempting to download activemq. It looks like version [3.9.3](http://mirrors.koehn.com/apache/activemq/activemq-cpp/) is the only version available now.

**Comment by smanders** [comment]
turns out I just needed a better URL - one that appears won't change as they move to new versions

**Comment by smanders** [comment]
completed with [commit](https://github.com/smanders/externpro/commit/d5d6a002b18a056275a55725a34af39d63005669) to dev branch
